config/routes.rb
Coach::Application.routes.draw do
	authenticated :user do
		root :to => 'home#index'
	end

	root :to => "home#index"
	devise_for :users
	
	resources :users, :only => :show do
		resources :schedules
		resources :boards
	end
	resources :home, :only => :index do
		collection do
			get 'plan'
		end
	end

	resources :functionalities
	resources :site_infos, :controller => "manager", :path => "manage"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.all
  end

  def plan
  	@user = User.where(:email => "congteng45@gmail.com").first
  	@boards = Board.where(:board_id => nil, :user_id => @user.id)
  end
end

app/helpers/home_helper.rb
module HomeHelper

	
	
end

app/views/home/index.html.erb
<hr>
进入网站规划设计页面 &nbsp;&nbsp;&nbsp;<%= link_to "click me", plan_home_index_path %>
<hr>
<% if @users %>

	<h5>注册用户列表</h5>

	<% @users.each do |user| %>
	  <p>User: <%=link_to user.name, user %></p>
	<% end %>
<% end -%>

<%= link_to "管理", site_infos_path %>

app/views/home/plan.html.erb
<%= content_for :styles do %>
	<%= stylesheet_link_tag "boards" %>
<% end -%>

<%= render "functionalities/labels" %>

<h3>开发规划(预览区域)</h3>
<span class="label label-default">网站分为两大模块（增肌/减肥）</span>


<div class='display_area'>
	<%= recursion_board_without_button @boards %>
</div>

<hr>

<h3>开发规划(编辑区域)</h3>

这里是用来增加最高级别模块的
<div class='add_top_b'>
	<%= simple_form_for Board.new, :remote => true do |f| %>
		<%= f.input :name, :label => "模块名称" %>
		<%= f.submit "增加模块" %>
	<% end -%>
</div>
<div class='display_area_btn'>
	<%= recursion_board_with_button @boards %>
</div>

<div class='addfoos'>
	<div class='close'>X</div>
	<%= simple_form_for Functionality.new, :remote => true do |f| %>
		<div class='info'>给<span></span>增加功能</div>
		<%= f.input :say, :label => "功能细节" %>
		<input type='hidden' name='b_id'>
		<%= f.submit "确认增加功能"%>
	<% end -%>
</div>

<div class='addboard'>
	<div class='close'>X</div>
	<%= simple_form_for Board.new, :remote => true do |f| %>
		<div class='info'>给<span></span>增加子模块</div>		
		<%= f.input :name, :label => "名称" %>
		<input type="hidden" name='b_id'>
		<%= f.submit "确认增加子模块" %>
	<% end -%>
</div>