config/routes.rb
Coach::Application.routes.draw do
	authenticated :user do
		root :to => 'home#index'
	end

	root :to => "home#index"
	devise_for :users
	
	resources :users, :only => :show do
		resources :schedules
		resources :boards
	end
	resources :home, :only => :index do
		collection do
			get 'plan'
		end
	end

	resources :functionalities
	resources :site_infos, :controller => "manager", :path => "manage"
end

app/models/functionality.rb
class Functionality
  	include Mongoid::Document
  	include Mongoid::Timestamps

  	field :say

  	# 0: todo, 1: doing, 2:done
	field :status, :type => Integer, :default => 0

	field :progress, :type => Integer, :default => 0

  	belongs_to :board

  	belongs_to :user

  	attr_accessible :say, :status, :progress
end

app/controllers/functionalities_controller.rb
class FunctionalitiesController < ApplicationController

	before_filter :which_user

	def which_user
		@user = User.find params[:user_id]
	end

	def index
		status = params[:status]
		@foos = Functionality.where(:status => status)						
	end

	def create
		f = Functionality.new params[:functionality]
		b_id = params[:b_id]
		p_board = Board.find b_id
		f.board = p_board
		f.save

		@user.functionalities << f

		@boards = @user.boards
	end

	def update

		f = Functionality.find params[:id]
		progress = params[:progress]
		if progress == 0.to_s
			f.update_attributes(:status => 0)
		elsif progress == 100.to_s
			f.update_attributes(:status => 2)
		else
			f.update_attributes(:status => 1)
		end
				
		f.update_attributes(:progress => progress)
		@foo = f
	end

	def destroy

		f = Functionality.find params[:id]
		f.destroy
	end

	def show

		@f = Functionality.find params[:id]
	end

end

app/helpers/functionalities_helper.rb
module FunctionalitiesHelper

	def rel_count status
		if status
			Functionality.where(:status => status).size	
		else
			Functionality.all.size	
		end
	end

	def b_count user
		Board.where(:user_id => user.id).size
	end
end

app/views/functionalities/_labels.html.erb
<div class='labels'>
	<ul>
		<li><span class="label label-default">共有<span class="label label-warning"><%= b_count(@user) %></span>个模块<span class="label label-important"><%= rel_count(nil) %></span>个功能,进度如下：</span></li>
		<ul>
			<li><span class="label label-important"><%= link_to "等待开发", functionalities_path(:status => "0") %> (<%= rel_count "0" %>)</span></li>
			<li><span class="label label-info"><%= link_to "正在开发", functionalities_path(:status => "1") %> (<%= rel_count "1" %>)</span></li>
			<li><span class="label label-success"><%= link_to "开发完成", functionalities_path(:status => "2") %> (<%= rel_count "2" %>)</span></li>
		</ul>
	</ul>
</div>

app/views/functionalities/create.js.erb
$('.display_area').html("<%= recursion_board_without_button @boards.where(:board_id => nil)%>")
$('.display_area_btn').html("<%= recursion_board_with_button @boards.where(:board_id => nil) %>")

$('.addfoos input[type=text]').val("")
$('.addfoos').hide("slow");

$('.labels').html("<%= j render 'functionalities/labels'%>")

app/views/functionalities/destroy.js.erb
$('.display_area').html("<%= recursion_board_without_button  @user.boards(:board_id => nil) %>")
$('.display_area_btn').html("<%= recursion_board_with_button  @user.boards(:board_id => nil) %>")

app/views/functionalities/index.html.erb
<%= content_for :styles do %>
	<%= stylesheet_link_tag "functionalities" %>
<% end -%>

<%= render "functionalities/labels" %>

<% @foos.each do |foo| %>
	<span id='label-<%= foo.id %>' class='label label-<%= foo_color foo %>'><a href='/functionalities/<%= foo.id%>'><%= foo.say %></a></span>

	<div class='f_foo'>
		<div class="progress progress-info progress-striped active">
			<div class="bar" style="width: <%= foo.progress %>%;"></div>
		</div>
		<span class='f_progress_chooser'>
			<a data-val='0' data-id='<%= foo.id%>'>0%</a> |
			<a data-val='20' data-id='<%= foo.id%>'>20%</a> |
			<a data-val='40' data-id='<%= foo.id%>'>40%</a> |
			<a data-val='60' data-id='<%= foo.id%>'>60%</a> | 
			<a data-val='80' data-id='<%= foo.id%>'>80%</a> | 
			<a data-val='100' data-id='<%= foo.id%>'>100%</a> 
		</span>
	</div>
<% end -%>

<% if @foos.empty? %>
	暂时没有...
<% end -%>

app/views/functionalities/show.html.erb
<%= content_for :styles do %>
	<%= stylesheet_link_tag "functionalities" %>
<% end -%>

<%= render "functionalities/labels" %>

<span id='label-<%= @f.id %>' class='label label-<%= foo_color @f %>'><a href='/functionalities/<%= @f.id%>'><%= @f.say %></a></span>

<div class='f_foo'>
	<div class="progress progress-info progress-striped active">
		<div class="bar" style="width: <%= @f.progress %>%;"></div>
	</div>

	<span class='f_progress_chooser'>
		<a data-val='0' data-id='<%= @f.id%>'>0%</a> |
		<a data-val='20' data-id='<%= @f.id%>'>20%</a> |
		<a data-val='40' data-id='<%= @f.id%>'>40%</a> |
		<a data-val='60' data-id='<%= @f.id%>'>60%</a> | 
		<a data-val='80' data-id='<%= @f.id%>'>80%</a> | 
		<a data-val='100' data-id='<%= @f.id%>'>100%</a> 
	</span>
</div>

app/views/functionalities/update.js.erb
$("#label-<%= @foo.id %>").attr("class", "label label-<%= foo_color @foo%>")
$('.labels').html("<%= j render 'functionalities/labels'%>")